(in-package :multi)
;;; Work on DEFGLOBAL global lexical variables for SBCL, it is requested! Let-pseudoglobals was on the right track, but it looks like the compiler must be modified.
(defmacro collect (var-and-list &body body)
  (let ((collector (gensym)))
    `(let ((,collector nil))
       (dolist (,(car var-and-list) ,(car (cdr var-and-list)))
	 (setf ,collector (cons (progn ,@body) ,collector)))
       (reverse ,collector))))
(defun drakma-no-octets (url)
  (let ((result (drakma:http-request url)))
    (if (stringp result)
	result
	(drakma::octets-to-string result))))
(defun getpage (uri)
  "Uri should be 'http(s)://domainname.blah.toplevel/blah/blah/blah'"
  (drakma-no-octets uri))
(defun multiuri (&rest urilist)
  "Deprecated function, use `uri' instead!"
  (progn (warn "Multiuri is deprecated, use `uri' instead. Consider:
multi::multiuri vs multi:uri. Isn't that a better name?")
         (apply #'uri urilist)))
(defun uri (&rest urilist)
  (let ((lock (gensym))
	(list (gensym))
	(uri (gensym)))
    (setf lock (make-lock))		;a gensym
    (setf list nil)
    (let ((thread-list (collect (var urilist)
			 (setf uri var)
			 (make-thread (lambda ()
					(let ((result (getpage uri)))
					  (with-lock-held (lock)
					    (setf list (cons result list)))))
				      :name uri))))
      (dolist (thread thread-list list)
	(join-thread thread)))))
